In [203]:
import pandas as pd
import numpy as np
from apyori import apriori
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import matplotlib.pyplot as plt
from sklearn import preprocessing
from mlxtend.preprocessing import TransactionEncoder
from sklearn.preprocessing import OneHotEncoder
from scipy.io import arff
from sklearn.preprocessing import Binarizer

In [204]:
#dataset = pd.read_csv('benign_dataset_final.csv')
dataset = pd.read_csv('thesis_final_dataset.csv')
dataset.head()

URL  Label  iframe_count  \
0                                      mediafire.com      0             5   
1                                               t.co      0             0   
2                                         kompas.com      0             3   
3  http://healthesouls.com/secure/Chase/5bfd37a75...      1             0   
4                                           etsy.com      0             3   

   small_area  line_counts  max_length_line   space_%  js_count  ext_js_count  \
0           1           77            10101  0.984381        33            16   
1           0           47              337  0.956935         1             0   
2           1         2056             6525  0.726826        53            26   
3           0          205             4070  0.954054         0             0   
4           2         5720             5342  0.833790        56            15   

   obfus_suspicious_func_count  var_function  dom_counts   Entropy  \
0                            0            57          10  3.238901   
1                            0             0           0  2.000000   
2                            8           252          80  2.921928   
3                            0             0           0  4.856231   
4                            0           129          23  3.000000   

   special char_ratio  suspicious_word  
0            0.000000                0  
1            0.000000                0  
2            0.000000                0  
3            0.045918                1  
4            0.000000                0

In [205]:
dataset.shape

(1200, 15)

In [206]:
dataset = dataset.iloc[:, 1:].values

In [207]:
transformer = Binarizer().fit(dataset)
df = transformer.transform(dataset)
print(df)

[[0. 1. 1. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 1. 1. 0.]
 [1. 0. 0. ... 1. 1. 0.]]


In [208]:
dataset = pd.DataFrame(df)
dataset.head()

0    1    2    3    4    5    6    7    8    9   10   11   12   13
0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0
1  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
2  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0
3  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0
4  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0

In [209]:
dataset.shape

(1200, 14)

In [210]:
new_data = dataset.rename(columns={0:'Label',1:'iframe_count',2:'small_area',3:'line_counts',4:'max_length_line',
                                   5:'space_%',6:'js_count',7:'ext_js_count',8:'obfus_suspicious_func_count',9:'var_function',
                                   10:'dom_counts',11:'Entropy',12:'special char_ratio',13:'suspicious_word'})
new_data.head()

Label  iframe_count  small_area  line_counts  max_length_line  space_%  \
0    0.0           1.0         1.0          1.0              1.0      1.0   
1    0.0           0.0         0.0          1.0              1.0      1.0   
2    0.0           1.0         1.0          1.0              1.0      1.0   
3    1.0           0.0         0.0          1.0              1.0      1.0   
4    0.0           1.0         1.0          1.0              1.0      1.0   

   js_count  ext_js_count  obfus_suspicious_func_count  var_function  \
0       1.0           1.0                          0.0           1.0   
1       1.0           0.0                          0.0           0.0   
2       1.0           1.0                          1.0           1.0   
3       0.0           0.0                          0.0           0.0   
4       1.0           1.0                          0.0           1.0   

   dom_counts  Entropy  special char_ratio  suspicious_word  
0         1.0      1.0                 0.0              0.0  
1         0.0      1.0                 0.0              0.0  
2         1.0      1.0                 0.0              0.0  
3         0.0      1.0                 1.0              1.0  
4         1.0      1.0                 0.0              0.0

In [218]:
frequent_itemsets = apriori(new_data, min_support=0.9, use_colnames=True)

In [219]:
frequent_itemsets

support                                          itemsets
0   0.960000                                     (line_counts)
1   0.959167                                 (max_length_line)
2   0.965000                                         (space_%)
3   1.000000                                         (Entropy)
4   0.959167                    (max_length_line, line_counts)
5   0.959167                            (space_%, line_counts)
6   0.960000                            (Entropy, line_counts)
7   0.958333                        (space_%, max_length_line)
8   0.959167                        (max_length_line, Entropy)
9   0.965000                                (space_%, Entropy)
10  0.958333           (space_%, max_length_line, line_counts)
11  0.959167           (max_length_line, Entropy, line_counts)
12  0.959167                   (space_%, Entropy, line_counts)
13  0.958333               (space_%, max_length_line, Entropy)
14  0.958333  (space_%, max_length_line, Entropy, line_counts)

In [220]:
frequent_itemsets.shape

(15, 2)

In [221]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=1)

In [223]:
rules

antecedents             consequents  \
0                         (max_length_line)           (line_counts)   
1                             (line_counts)               (Entropy)   
2                         (max_length_line)               (Entropy)   
3                                 (space_%)               (Entropy)   
4                (space_%, max_length_line)           (line_counts)   
5                (max_length_line, Entropy)           (line_counts)   
6            (max_length_line, line_counts)               (Entropy)   
7                         (max_length_line)  (Entropy, line_counts)   
8                    (space_%, line_counts)               (Entropy)   
9                (space_%, max_length_line)               (Entropy)   
10      (space_%, max_length_line, Entropy)           (line_counts)   
11  (space_%, max_length_line, line_counts)               (Entropy)   
12               (space_%, max_length_line)  (Entropy, line_counts)   

    antecedent support  consequent support   support  confidence      lift  \
0             0.959167                0.96  0.959167         1.0  1.041667   
1             0.960000                1.00  0.960000         1.0  1.000000   
2             0.959167                1.00  0.959167         1.0  1.000000   
3             0.965000                1.00  0.965000         1.0  1.000000   
4             0.958333                0.96  0.958333         1.0  1.041667   
5             0.959167                0.96  0.959167         1.0  1.041667   
6             0.959167                1.00  0.959167         1.0  1.000000   
7             0.959167                0.96  0.959167         1.0  1.041667   
8             0.959167                1.00  0.959167         1.0  1.000000   
9             0.958333                1.00  0.958333         1.0  1.000000   
10            0.958333                0.96  0.958333         1.0  1.041667   
11            0.958333                1.00  0.958333         1.0  1.000000   
12            0.958333                0.96  0.958333         1.0  1.041667   

    leverage  conviction  
0   0.038367         inf  
1   0.000000         inf  
2   0.000000         inf  
3   0.000000         inf  
4   0.038333         inf  
5   0.038367         inf  
6   0.000000         inf  
7   0.038367         inf  
8   0.000000         inf  
9   0.000000         inf  
10  0.038333         inf  
11  0.000000         inf  
12  0.038333         inf